version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nautilus
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: